// A MET (Metabolic Equivalent of Task) is a ratio to resting energy
// expenditure — 1 MET is roughly the energy cost of sitting quietly.
// Values below are drawn from the 2024 Adult Compendium of Physical
// Activities (Herrmann et al., Journal of Sport and Health Science,
// 2024 — the current peer-reviewed standard, superseding the 2011
// edition), narrowed to recreational/everyday activities a general
// fitness app user would actually look up, with wattage- and
// cadence-specific gym-equipment variants excluded in favor of their
// speed/effort-described equivalents.
export const MET_SOURCE = {
  name: '2024 Adult Compendium of Physical Activities',
  authors: 'Herrmann SD, et al.',
  journal: 'Journal of Sport and Health Science, 2024',
};

// ACSM's standard three-tier intensity classification, matching the
// Light / Moderate / Vigorous split used everywhere else in Groove.
export function metIntensity(met) {
  if (met < 3) return 'Light';
  if (met <= 6) return 'Moderate';
  return 'Vigorous';
}

export const MET_ACTIVITIES = [
  { name: "Bicycling, eccentric only, 100 to 149 W", met: 2.3, category: "Bicycling" },
  { name: "Bicycling, leisure 5.5 mph", met: 3.5, category: "Bicycling" },
  { name: "E-bike (electrically assisted) with high electronic support", met: 4.0, category: "Bicycling" },
  { name: "Bicycling, eccentric only, 200 W", met: 4.0, category: "Bicycling" },
  { name: "Bicycling, self-selected easy pace", met: 4.3, category: "Bicycling" },
  { name: "Unicycling", met: 5.0, category: "Bicycling" },
  { name: "Bicycling, concentric only, 100 W", met: 5.5, category: "Bicycling" },
  { name: "Bicycling, on dirt or farm road, moderate pace", met: 5.8, category: "Bicycling" },
  { name: "Bicycling, leisure, 9.4 mph", met: 5.8, category: "Bicycling" },
  { name: "E-bike (electrically assisted) with light electronic support", met: 6.0, category: "Bicycling" },
  { name: "Bicycling, to/from work, self selected pace", met: 6.8, category: "Bicycling" },
  { name: "Bicycling, 10-11.9 mph, leisure, slow, light effort", met: 6.8, category: "Bicycling" },
  { name: "E-bike (electrically assisted) without electronic support", met: 6.8, category: "Bicycling" },
  { name: "Bicycling, stationary, general", met: 6.8, category: "Bicycling" },
  { name: "Bicycling, general", met: 7.0, category: "Bicycling" },
  { name: "Bicycling, self-selected moderate pace", met: 7.0, category: "Bicycling" },
  { name: "Bicycling, 12-13.9 mph, leisure, moderate effort", met: 8.0, category: "Bicycling" },
  { name: "Bicycling, BMX", met: 8.5, category: "Bicycling" },
  { name: "Bicycling, mountain, general", met: 8.5, category: "Bicycling" },
  { name: "Bicycling, interactive virtual cycling, indoor cycle ergometer", met: 8.8, category: "Bicycling" },
  { name: "Bicycling, high intensity interval training", met: 8.8, category: "Bicycling" },
  { name: "Bicycling, self-selected vigorous pace", met: 9.0, category: "Bicycling" },
  { name: "Bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort", met: 10.0, category: "Bicycling" },
  { name: "Bicycling, concentric only, 200 W", met: 11.0, category: "Bicycling" },
  { name: "Bicycling, 16-19 mph, racing/not drafting or >19 mph drafting, very fast, racing general", met: 12.0, category: "Bicycling" },
  { name: "Bicycling, mountain, uphill, vigorous", met: 14.0, category: "Bicycling" },
  { name: "Bicycling, mountain, competitive racing", met: 16.0, category: "Bicycling" },
  { name: "Bicycling, >20 mph, racing, not drafting", met: 16.8, category: "Bicycling" },
  { name: "Whirlpool, sitting", met: 1.3, category: "Conditioning Exercise" },
  { name: "Pilates, traditional, mat", met: 1.8, category: "Conditioning Exercise" },
  { name: "Arm Ergometer, hand bike, 15W", met: 2.0, category: "Conditioning Exercise" },
  { name: "Yoga, Nadisodhana", met: 2.0, category: "Conditioning Exercise" },
  { name: "Stretching, mild", met: 2.3, category: "Conditioning Exercise" },
  { name: "Yoga, Hatha", met: 2.3, category: "Conditioning Exercise" },
  { name: "Yoga, General", met: 2.3, category: "Conditioning Exercise" },
  { name: "Balance Exercise Assist Robot (BEAR), simulated skiing, tennis, rodeo", met: 2.3, category: "Conditioning Exercise" },
  { name: "Video, exercise workouts, TV conditioning programs (e.g., yoga, stretching, seated), light effort", met: 2.5, category: "Conditioning Exercise" },
  { name: "Yoga, Vinyasa", met: 2.7, category: "Conditioning Exercise" },
  { name: "Calisthenics (e.g., curl ups, abdominal crunches, plank),  light effort", met: 2.8, category: "Conditioning Exercise" },
  { name: "Pilates, general", met: 2.8, category: "Conditioning Exercise" },
  { name: "Therapeutic exercise ball, Fitball exercise", met: 2.8, category: "Conditioning Exercise" },
  { name: "Upper body exercise, arm ergometer, general, light", met: 2.8, category: "Conditioning Exercise" },
  { name: "Arm Ergometer, hand bike, 25-30W", met: 2.8, category: "Conditioning Exercise" },
  { name: "Sit to stand exercise, 6-12 times/min", met: 2.8, category: "Conditioning Exercise" },
  { name: "Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), general", met: 3.0, category: "Conditioning Exercise" },
  { name: "Yoga, Hot", met: 3.0, category: "Conditioning Exercise" },
  { name: "Wand exercise, Life-Build-Line", met: 3.0, category: "Conditioning Exercise" },
  { name: "Circuit training, light effort", met: 3.5, category: "Conditioning Exercise" },
  { name: "Curves™ exercise routines in women", met: 3.5, category: "Conditioning Exercise" },
  { name: "Resistance (weight) training, multiple exercises, 8-15 reps at varied resistance", met: 3.5, category: "Conditioning Exercise" },
  { name: "Arm Ergometer, hand bike, 45W", met: 3.5, category: "Conditioning Exercise" },
  { name: "Yoga, Surya Namaskar", met: 3.5, category: "Conditioning Exercise" },
  { name: "Calisthenics (e.g., pushups, sit ups, pull-ups, lunges), moderate effort", met: 3.8, category: "Conditioning Exercise" },
  { name: "Home exercise, general", met: 3.8, category: "Conditioning Exercise" },
  { name: "Video, exercise workouts, TV conditioning programs (e.g., cardio-resistance training), moderate", met: 4.0, category: "Conditioning Exercise" },
  { name: "Yoga, Power", met: 4.0, category: "Conditioning Exercise" },
  { name: "Sit to stand exercise, 18-24 times/min", met: 4.0, category: "Conditioning Exercise" },
  { name: "Pole dancing, exercise class", met: 4.5, category: "Conditioning Exercise" },
  { name: "Aerobic dance, low impact, moderate effort", met: 4.8, category: "Conditioning Exercise" },
  { name: "Army type obstacle course exercise, boot camp training program", met: 5.0, category: "Conditioning Exercise" },
  { name: "Circuit training, moderate effort", met: 5.0, category: "Conditioning Exercise" },
  { name: "Elliptical trainer, moderate effort", met: 5.0, category: "Conditioning Exercise" },
  { name: "Resistance (weight) training, squats, deadlift, slow or explosive effort", met: 5.0, category: "Conditioning Exercise" },
  { name: "Health club exercise classes general, gym/weight training combined in one visit", met: 5.0, category: "Conditioning Exercise" },
  { name: "Water aerobics, water calisthenics, water exercise", met: 5.3, category: "Conditioning Exercise" },
  { name: "Native New Zealander PA, (e.g., Haka Powhiri, Poi, Moteatea, etc.), general moderate effort", met: 5.3, category: "Conditioning Exercise" },
  { name: "Aerobic, step, with 4-inch step", met: 5.5, category: "Conditioning Exercise" },
  { name: "Zumba, home video", met: 5.5, category: "Conditioning Exercise" },
  { name: "Resistance Training, circuit, reciprocol supersets, peripheral hear action training", met: 5.8, category: "Conditioning Exercise" },
  { name: "Hooping (formerly known as hula® hooping)", met: 5.8, category: "Conditioning Exercise" },
  { name: "Circuit training, body weight exercises", met: 6.0, category: "Conditioning Exercise" },
  { name: "Slimnastics, jazzercise", met: 6.0, category: "Conditioning Exercise" },
  { name: "Video, exercise workouts, TV conditioning programs (e.g., cardio-resistance training), vigorous", met: 6.0, category: "Conditioning Exercise" },
  { name: "Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), high intensity", met: 6.5, category: "Conditioning Exercise" },
  { name: "Zumba, group class", met: 6.5, category: "Conditioning Exercise" },
  { name: "Ski machine, general", met: 6.8, category: "Conditioning Exercise" },
  { name: "Teaching exercise classes (e.g., aerobic, water)", met: 6.8, category: "Conditioning Exercise" },
  { name: "Native New Zealander PA, general, vigorous effort", met: 6.8, category: "Conditioning Exercise" },
  { name: "High intensity interval exercise,  moderate effort", met: 7.0, category: "Conditioning Exercise" },
  { name: "Aerobic, general", met: 7.3, category: "Conditioning Exercise" },
  { name: "Aerobic, step, with 6 – 8 inch step", met: 7.3, category: "Conditioning Exercise" },
  { name: "Rowing, stationary ergometer, general, vigorous effort", met: 7.3, category: "Conditioning Exercise" },
  { name: "Calisthenics (e.g., pushups, sit ups, pull-ups, jumping jacks, burpees, battling ropes), vigorous effort", met: 7.5, category: "Conditioning Exercise" },
  { name: "Circuit training, including kettlebells, some aerobic movement with minimal rest, general, vigorous intensity", met: 7.5, category: "Conditioning Exercise" },
  { name: "Bench step class, general", met: 7.8, category: "Conditioning Exercise" },
  { name: "Health club exercise, conditioning classes", met: 7.8, category: "Conditioning Exercise" },
  { name: "Virtual Reality Fitness,  Supernatural™ “Flow”, “Boxing\" vigorous intensity", met: 7.9, category: "Conditioning Exercise" },
  { name: "Aerobic dance, high impact, vigorous effort", met: 8.0, category: "Conditioning Exercise" },
  { name: "Yoga, Hatha, high intensity", met: 8.0, category: "Conditioning Exercise" },
  { name: "Pound, combination of Pilates and body movements with drumming", met: 8.5, category: "Conditioning Exercise" },
  { name: "Aerobic, step, with 10 – 12 inch step", met: 9.0, category: "Conditioning Exercise" },
  { name: "Elliptical trainer, vigorous effort", met: 9.0, category: "Conditioning Exercise" },
  { name: "Jumping rope, Digi-Jump Maching, 120 jumps/minute", met: 9.0, category: "Conditioning Exercise" },
  { name: "Impulse Training System, Inertial Exercise Trainer", met: 9.0, category: "Conditioning Exercise" },
  { name: "Stair treadmill ergometer, general", met: 9.3, category: "Conditioning Exercise" },
  { name: "ExerCube, workout series", met: 9.3, category: "Conditioning Exercise" },
  { name: "Therapeutic exercise ball, Fitball exercise, high intensity", met: 9.5, category: "Conditioning Exercise" },
  { name: "Kettle bell swings", met: 9.8, category: "Conditioning Exercise" },
  { name: "Aerobic dance wearing 10-15 lb weights", met: 10.0, category: "Conditioning Exercise" },
  { name: "Ski ergometer, cross country, double poling, slow to moderate speed", met: 10.5, category: "Conditioning Exercise" },
  { name: "Slide board exercise, general", met: 10.5, category: "Conditioning Exercise" },
  { name: "Rope skipping exercise, general", met: 11.0, category: "Conditioning Exercise" },
  { name: "Shuttle running, forward/backward/lateral", met: 11.0, category: "Conditioning Exercise" },
  { name: "High intensity interval exercise,  burpees, mountain climbers, squat jumps, Tabata, vigorous effort", met: 11.0, category: "Conditioning Exercise" },
  { name: "Blackbox Immersive virtual reality exergaming system, vigorous intensity", met: 13.0, category: "Conditioning Exercise" },
  { name: "Ski ergometer, cross country, double poling, fast to maximum speed", met: 18.0, category: "Conditioning Exercise" },
  { name: "Ballroom, slow, examples: waltz, foxtrot, slow dancing, samba tango, rumba, 19th century dance, mambo, cha cha", met: 3.0, category: "Dancing" },
  { name: "Caribbean dance (Abakua, Beguine, Bellair, Bongo, Brukin’s, Caribbean Quadrills, Dinki  Mini, Gere, Gumbay, Ibo, Jonkonnu,", met: 3.5, category: "Dancing" },
  { name: "Contemporary dancing, general", met: 3.8, category: "Dancing" },
  { name: "Contemporary dancing, nightclub", met: 4.3, category: "Dancing" },
  { name: "Ethnic or cultural dancing (e.g. Greek, Middle Eastern, hula, salsa, merengue, bamba y plena,  flamenco, belly, and swing)", met: 4.5, category: "Dancing" },
  { name: "Jazz dancing, general", met: 4.5, category: "Dancing" },
  { name: "Tap", met: 4.8, category: "Dancing" },
  { name: "Salsa Dancing, with partner", met: 4.8, category: "Dancing" },
  { name: "Ballet, modern, or jazz general, rehearsal or class", met: 5.0, category: "Dancing" },
  { name: "Folk dancing, moderate effort", met: 5.0, category: "Dancing" },
  { name: "Chinese square dance, Ballet & Tibetan dance", met: 5.5, category: "Dancing" },
  { name: "Anishinaabe Jingle dancing, brisk pace, other traditional American Indian dancing performed by women, moderate effort", met: 5.5, category: "Dancing" },
  { name: "Square Dancing, American Western, country", met: 5.5, category: "Dancing" },
  { name: "Polynesian dance, Hawaiian hula slow, Maori haka, Tongan", met: 5.8, category: "Dancing" },
  { name: "Afro-Cuban salsa (Cuban cha-cha-cha, mambo, Afro rumba, contratiempo son steps, orisha/santo movements)", met: 6.0, category: "Dancing" },
  { name: "Ballroom Dance, Recreational (Waltz, Foxtrot, Cha-cha, Swing)", met: 6.0, category: "Dancing" },
  { name: "Ballet exercises (plie, tendus, jetes, rond de Jambes, fondus, grand battement, grand adage, sautes, temp Leve's)", met: 6.3, category: "Dancing" },
  { name: "Salsa dancing, to a video", met: 6.3, category: "Dancing" },
  { name: "Ballet, modern, or jazz, performance, vigorous effort", met: 6.8, category: "Dancing" },
  { name: "Polynesian dance, Hawaiian hula fast, Samoan sasa, Fijian style fast, Filipino Tinikling", met: 7.0, category: "Dancing" },
  { name: "Chinese square dance, aerobic dance", met: 7.3, category: "Dancing" },
  { name: "Flamenco dance", met: 8.5, category: "Dancing" },
  { name: "Polynesian dance, Samoan slap, Tahitian", met: 8.8, category: "Dancing" },
  { name: "Nightclub or folk dancing, vigorous effort (e.g., nightclub, disco, folk, line dancing, Irish step dancing, polka, contra)", met: 9.8, category: "Dancing" },
  { name: "Musical Theater, Singing/dancing", met: 10.3, category: "Dancing" },
  { name: "Ballroom dancing, competitive, general", met: 11.3, category: "Dancing" },
  { name: "ballroom dance, DanceSport competition (modern waltz, tango, Viennese waltz, slow fox, quick step, samba, chacha, rumba,", met: 13.0, category: "Dancing" },
  { name: "Knitting, sewing, light effort, wrapping presents, sitting", met: 1.3, category: "Home Activities" },
  { name: "Handwashing", met: 1.3, category: "Home Activities" },
  { name: "Reclining with baby", met: 1.5, category: "Home Activities" },
  { name: "Ironing", met: 1.8, category: "Home Activities" },
  { name: "Elder care, disabled adult, feeding, combing hair, light effort, only active periods", met: 1.8, category: "Home Activities" },
  { name: "Wash dishes, standing or in general (not broken into stand/walk components)", met: 2.0, category: "Home Activities" },
  { name: "Wash dishes, clearing dishes from table, walking, light effort", met: 2.0, category: "Home Activities" },
  { name: "Cooking or food preparation - standing or sitting or in general (not broken into stand/walk components), manual appliances,", met: 2.0, category: "Home Activities" },
  { name: "Laundry, fold or hang clothes, sitting", met: 2.0, category: "Home Activities" },
  { name: "Laundry,  putting away clothes, gathering clothes to pack, putting away laundry, implied walking", met: 2.0, category: "Home Activities" },
  { name: "Scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, light effort", met: 2.0, category: "Home Activities" },
  { name: "Watering  plants", met: 2.0, category: "Home Activities" },
  { name: "Standing, light effort tasks (pump gas, change light bulb, etc.)", met: 2.0, category: "Home Activities" },
  { name: "Standing, holding child", met: 2.0, category: "Home Activities" },
  { name: "Child care: sitting or kneeling, dressing, bathing, grooming, feeding, occasional lifting of child-light effort, general", met: 2.0, category: "Home Activities" },
  { name: "Breastfeeding, sitting or reclining", met: 2.0, category: "Home Activities" },
  { name: "Cleaning, sweeping, slow, light effort", met: 2.3, category: "Home Activities" },
  { name: "Cutting and smoking fish, drying fish or meat", met: 2.3, category: "Home Activities" },
  { name: "Cooking or food preparation, walking", met: 2.3, category: "Home Activities" },
  { name: "Serving food, setting/cleaning table, implied walking or standing", met: 2.3, category: "Home Activities" },
  { name: "Non-food shopping, with or without cart, standing or walking", met: 2.3, category: "Home Activities" },
  { name: "Laundry, fold or hang clothes, put clothes in washer or dryer, packing suitcase, washing clothes by hand,  implied standing,", met: 2.3, category: "Home Activities" },
  { name: "Sitting, playing with child(ren), light effort, only active periods", met: 2.3, category: "Home Activities" },
  { name: "Animal care, household animals, general", met: 2.3, category: "Home Activities" },
  { name: "Mopping, standing, light effort", met: 2.5, category: "Home Activities" },
  { name: "Dusting or polishing furniture, general", met: 2.5, category: "Home Activities" },
  { name: "Cleaning, general (straightening up, changing linen, carrying out trash), light effort", met: 2.5, category: "Home Activities" },
  { name: "Feeding household animals", met: 2.5, category: "Home Activities" },
  { name: "Putting away groceries (e.g. carrying groceries, carrying packages)", met: 2.5, category: "Home Activities" },
  { name: "Building a fire inside", met: 2.5, category: "Home Activities" },
  { name: "Walking and carrying small child, child weighing less than 15 lbs", met: 2.5, category: "Home Activities" },
  { name: "Child care, infant, general", met: 2.5, category: "Home Activities" },
  { name: "Sit, playing with animals, light, only active period", met: 2.5, category: "Home Activities" },
  { name: "Multiple household tasks all at once, light effort", met: 2.8, category: "Home Activities" },
  { name: "Sewing with a machine", met: 2.8, category: "Home Activities" },
  { name: "Standing, playing with child(ren), light effort, only active periods", met: 2.8, category: "Home Activities" },
  { name: "Stand, playing with animals, light effort, only active periods", met: 2.8, category: "Home Activities" },
  { name: "Walk or run, playing with animals, general, light effort, only active periods", met: 2.8, category: "Home Activities" },
  { name: "Vacuuming, general, moderate effort", met: 3.0, category: "Home Activities" },
  { name: "Butchering animals, small", met: 3.0, category: "Home Activities" },
  { name: "Cooking Indian bread or other food on an outside stove", met: 3.0, category: "Home Activities" },
  { name: "Making bed, changing linens", met: 3.0, category: "Home Activities" },
  { name: "Sweeping garage, sidewalk, or outside house", met: 3.0, category: "Home Activities" },
  { name: "Implied walking, putting away household items, moderate effort", met: 3.0, category: "Home Activities" },
  { name: "Walking and carrying small child, child weighing 15 lbs or more", met: 3.0, category: "Home Activities" },
  { name: "Elder care, disabled adult, bathing, dressing, moving into and out of bed, only active periods", met: 3.0, category: "Home Activities" },
  { name: "Cleaning, sweeping carpet or floors, general", met: 3.3, category: "Home Activities" },
  { name: "Cleaning windows, washing windows, general", met: 3.3, category: "Home Activities" },
  { name: "Multiple household tasks all at once, moderate effort", met: 3.3, category: "Home Activities" },
  { name: "Cleaning, house or cabin, general, moderate effort", met: 3.3, category: "Home Activities" },
  { name: "Kitchen activity, general, (e.g., cooking, washing dishes, cleaning up) moderate effort", met: 3.3, category: "Home Activities" },
  { name: "Food shopping with or without a grocery cart; carrying a 10 lb bag; standing or walking", met: 3.3, category: "Home Activities" },
  { name: "Cleaning  heavy or major (e.g., wash car, clean garage), moderate effort", met: 3.5, category: "Home Activities" },
  { name: "Cleaning, mopping, standing, moderate effort", met: 3.5, category: "Home Activities" },
  { name: "Cooking or food preparation, moderate effort", met: 3.5, category: "Home Activities" },
  { name: "carrying groceries, on level ground, walking", met: 3.5, category: "Home Activities" },
  { name: "Scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, moderate effort", met: 3.5, category: "Home Activities" },
  { name: "Walking, moderate effort tasks, non-cleaning (readying to leave, shut/lock doors, close windows, etc.", met: 3.5, category: "Home Activities" },
  { name: "Walking/running, playing with child(ren), moderate effort, only active periods", met: 3.5, category: "Home Activities" },
  { name: "Child care: standing, dressing, bathing, grooming, feeding, occasional lifting of child- light effort", met: 3.5, category: "Home Activities" },
  { name: "Standing, bathing dog", met: 3.5, category: "Home Activities" },
  { name: "Cleaning, sweeping, fast, moderate effort", met: 3.8, category: "Home Activities" },
  { name: "Standing, packing/unpacking boxes, occasional lifting lightweight household items, loading or unloading items into a car,", met: 3.8, category: "Home Activities" },
  { name: "Tanning hides, general", met: 4.0, category: "Home Activities" },
  { name: "Laundry,  moderate effort", met: 4.0, category: "Home Activities" },
  { name: "Walk/run, playing with animals, moderate effort, only active periods", met: 4.0, category: "Home Activities" },
  { name: "Multiple household tasks all at once, vigorous effort", met: 4.3, category: "Home Activities" },
  { name: "Polishing floors, standing, walking slowly, using electric polishing machine", met: 4.5, category: "Home Activities" },
  { name: "Organizing a room", met: 4.8, category: "Home Activities" },
  { name: "Maple syruping/sugar bushing (including carrying buckets, carrying wood)", met: 5.0, category: "Home Activities" },
  { name: "Moving, lifting light loads", met: 5.0, category: "Home Activities" },
  { name: "Walk/run, playing with animals, vigorous effort, only active periods", met: 5.0, category: "Home Activities" },
  { name: "Carrying groceries upstairs", met: 5.3, category: "Home Activities" },
  { name: "Moving furniture, household items, carrying boxes", met: 5.8, category: "Home Activities" },
  { name: "Walking/running, playing with child(ren), vigorous effort, only active periods", met: 5.8, category: "Home Activities" },
  { name: "Butchering animals, large, vigorous effort", met: 6.0, category: "Home Activities" },
  { name: "Scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, vigorous effort", met: 6.5, category: "Home Activities" },
  { name: "Moving household items upstairs, carrying boxes or furniture", met: 9.0, category: "Home Activities" },
  { name: "gardening, general", met: 2.0, category: "Lawn & Garden" },
  { name: "Yardwork, general, light effort", met: 2.3, category: "Lawn & Garden" },
  { name: "Operating snow blower, walking", met: 2.5, category: "Lawn & Garden" },
  { name: "Planting, potting, transplanting seedlings or plants, light effort", met: 2.6, category: "Lawn & Garden" },
  { name: "Driving tractor", met: 2.8, category: "Lawn & Garden" },
  { name: "Riding snow blower", met: 3.0, category: "Lawn & Garden" },
  { name: "Walking, applying fertilizer or seeding a lawn, push applicator", met: 3.0, category: "Lawn & Garden" },
  { name: "Implied walking/standing - picking up yard, light, picking flowers or vegetables", met: 3.0, category: "Lawn & Garden" },
  { name: "Walking, gathering gardening tools", met: 3.0, category: "Lawn & Garden" },
  { name: "Trimming shrubs or trees, power cutter, using leaf blower, edger, moderate effort", met: 3.3, category: "Lawn & Garden" },
  { name: "Clearing light brush, thinning garden, moderate effort", met: 3.5, category: "Lawn & Garden" },
  { name: "Digging, spading, filling garden, composting, light-to-moderate effort", met: 3.5, category: "Lawn & Garden" },
  { name: "Picking fruit or coffee from trees, moderate effort", met: 3.5, category: "Lawn & Garden" },
  { name: "Trimming shrubs or trees, manual cutter", met: 3.8, category: "Lawn & Garden" },
  { name: "Weeding, cultivating garden, light-to-moderate effort", met: 3.8, category: "Lawn & Garden" },
  { name: "Gardening, general, moderate effort", met: 3.8, category: "Lawn & Garden" },
  { name: "Irrigation channels, opening and closing ports", met: 4.0, category: "Lawn & Garden" },
  { name: "Raking lawn or leaves, moderate effort", met: 4.0, category: "Lawn & Garden" },
  { name: "Raking roof with snow rake", met: 4.0, category: "Lawn & Garden" },
  { name: "Sacking grass, leaves", met: 4.0, category: "Lawn & Garden" },
  { name: "Watering lawn or garden, standing or walking", met: 4.0, category: "Lawn & Garden" },
  { name: "Yardwork, general, moderate effort", met: 4.0, category: "Lawn & Garden" },
  { name: "Carrying, loading or stacking wood, loading/unloading or carrying lumber, light-to- moderate effort", met: 4.1, category: "Lawn & Garden" },
  { name: "Planting seedlings, shrubs, stooping, moderate effort", met: 4.3, category: "Lawn & Garden" },
  { name: "Planting crops or garden, stooping, moderate effort", met: 4.3, category: "Lawn & Garden" },
  { name: "Chopping wood, splitting logs, moderate effort", met: 4.5, category: "Lawn & Garden" },
  { name: "Planting trees", met: 4.5, category: "Lawn & Garden" },
  { name: "Harvesting Produce, Picking fruit off trees, gleaning fruits, picking fruits/vegetables, climbing ladder to pick fruit, vigorous", met: 4.5, category: "Lawn & Garden" },
  { name: "Wheel barrow, pushing garden cart or wheelbarrow, general", met: 4.8, category: "Lawn & Garden" },
  { name: "Digging sandbox, shoveling sand", met: 5.0, category: "Lawn & Garden" },
  { name: "Laying sod", met: 5.0, category: "Lawn & Garden" },
  { name: "Mowing lawn, walk, power mower,  moderate or vigorous effort", met: 5.0, category: "Lawn & Garden" },
  { name: "Weeding, cultivating garden, using hoe moderate-to-vigorous effort", met: 5.0, category: "Lawn & Garden" },
  { name: "Felling trees, small-medium size", met: 5.3, category: "Lawn & Garden" },
  { name: "Shoveling snow, by hand, moderate effort", met: 5.3, category: "Lawn & Garden" },
  { name: "Carrying, loading or stacking wood, loading/unloading or carrying lumber, moderate effort", met: 5.5, category: "Lawn & Garden" },
  { name: "Mowing lawn, general, walking, moderate effort", met: 5.5, category: "Lawn & Garden" },
  { name: "Shoveling dirt or mud", met: 5.5, category: "Lawn & Garden" },
  { name: "Gardening with heavy power tools, using chain saw, tilling a garden", met: 5.8, category: "Lawn & Garden" },
  { name: "Wheel barrow, pushing large garden cart or heavy wheelbarrow up to 150kg", met: 6.0, category: "Lawn & Garden" },
  { name: "Yardwork, general, vigorous effort", met: 6.0, category: "Lawn & Garden" },
  { name: "Clearing land, haul brush, undergrowth, or ground, vigorous effort", met: 6.3, category: "Lawn & Garden" },
  { name: "Laying crushed rock or gravel", met: 6.3, category: "Lawn & Garden" },
  { name: "Chopping wood, splitting logs, vigorous effort", met: 6.5, category: "Lawn & Garden" },
  { name: "Digging, spading, filling garden, composting, vigorous effort", met: 7.3, category: "Lawn & Garden" },
  { name: "Shoveling snow, by hand, vigorous effort", met: 7.5, category: "Lawn & Garden" },
  { name: "Felling trees, large size", met: 8.3, category: "Lawn & Garden" },
  { name: "Jogging 2.6 to 3.7 mph", met: 3.3, category: "Running" },
  { name: "Jogging on a mini-tramp", met: 4.5, category: "Running" },
  { name: "Jogging, in place", met: 4.8, category: "Running" },
  { name: "Running/jogging, curved treadmill, 3.0 to 3.9 mph", met: 5.3, category: "Running" },
  { name: "Running downhill, 5.0 to 5.9 mph, -10% to -15%", met: 5.8, category: "Running" },
  { name: "Running, 4 to 4.2 mph (13 min/mile)", met: 6.5, category: "Running" },
  { name: "Running/jogging, curved treadmill, 4.0 to 4.9 mph", met: 6.5, category: "Running" },
  { name: "Jogging, general, self-selected pace", met: 7.5, category: "Running" },
  { name: "Running downhill, 6.0 to 6.9 mph, -10% to -15%", met: 7.5, category: "Running" },
  { name: "Running 4.3 to 4.8 mph", met: 7.8, category: "Running" },
  { name: "Running, barefoot, 3.5-5.9 mph", met: 7.8, category: "Running" },
  { name: "Running, training, pushing a wheelchair or baby carrier", met: 8.0, category: "Running" },
  { name: "Running, jogging stroller, indoors, 5 mph", met: 8.0, category: "Running" },
  { name: "Running, 5.0 to 5.2 mph (12 min/mile)", met: 8.5, category: "Running" },
  { name: "Running, 5.0 - 5.9 mph, 1.0 to 3.0 kg backpack", met: 8.5, category: "Running" },
  { name: "Running uphill, 0.6 to 0.79 mph, 30% incline", met: 8.8, category: "Running" },
  { name: "Running, 5.5 -5.8 mph", met: 9.0, category: "Running" },
  { name: "Running downhill, 7.0 to 8.9 mph, -10% to -15%", met: 9.0, category: "Running" },
  { name: "Running, jogging stroller, indoors, 6 mph", met: 9.0, category: "Running" },
  { name: "Running, 6-6.3 mph (10 min/mile)", met: 9.3, category: "Running" },
  { name: "Running, cross country", met: 9.3, category: "Running" },
  { name: "Running downhill, 6.0 to 7.9 mph, -3% to -9%", met: 9.3, category: "Running" },
  { name: "Running, 6.0 - 6.9 mph, 1.0 to 3.0 kg backpack", met: 9.5, category: "Running" },
  { name: "Running, 7.0 - 7.9 mph, 1.0 to 3.0 kg backpack", met: 9.8, category: "Running" },
  { name: "Running, on a track, team practice", met: 10.0, category: "Running" },
  { name: "Running, jogging stroller, outdoors, 5 mph", met: 10.0, category: "Running" },
  { name: "Running uphill, 4.5mph, 5% incline", met: 10.3, category: "Running" },
  { name: "Running uphill, 0.8 to 0.99 mph, 30% incline", met: 10.3, category: "Running" },
  { name: "Running, 6.7 mph (9 min/mile)", met: 10.5, category: "Running" },
  { name: "Running, self-selected pace", met: 10.5, category: "Running" },
  { name: "Running, 7 mph (8.5 min/mile)", met: 11.0, category: "Running" },
  { name: "Running curved treadmill, 5.0 to 5.9 mph", met: 11.0, category: "Running" },
  { name: "Running, jogging stroller, outdoors, 6 mph", met: 11.5, category: "Running" },
  { name: "Skipping, 5.5-6.0 mph", met: 11.5, category: "Running" },
  { name: "Running, 7.5 mph (8 min/mile)", met: 11.8, category: "Running" },
  { name: "Running uphill, 1.0 to 1.19 mph, 30% incline", met: 11.8, category: "Running" },
  { name: "Running, 8 mph (7.5 min/mile)", met: 12.0, category: "Running" },
  { name: "Running curved treadmill, 7.0 to 7.9 mph", met: 12.0, category: "Running" },
  { name: "Running, 8.0 - 8.9 mph, 1.0 to 3.0 kg backpack", met: 12.0, category: "Running" },
  { name: "Running, barefoot, 6.0-7.9 mph", met: 12.0, category: "Running" },
  { name: "Running, 8.6 mph (7 min/mile)", met: 12.5, category: "Running" },
  { name: "Running, 9 mph (6.5 min/mile)", met: 13.0, category: "Running" },
  { name: "Triathlon, Running", met: 13.0, category: "Running" },
  { name: "Running, marathon", met: 13.3, category: "Running" },
  { name: "Running uphill, 6.0 mph, 5% incline", met: 13.3, category: "Running" },
  { name: "Running uphill, 1.2 to 1.39 mph, 30-40% incline", met: 13.5, category: "Running" },
  { name: "Running, barefoot, 8.0-8.9 mph", met: 13.5, category: "Running" },
  { name: "Running downhill, 8.0 to 10.5 mph, -3% to -9%", met: 13.8, category: "Running" },
  { name: "Running curved treadmill, 8.0 to 8.9 mph", met: 14.0, category: "Running" },
  { name: "Running, 9.3 to 9.6 mph", met: 14.8, category: "Running" },
  { name: "Running, 10 mph (6 min/mile)", met: 14.8, category: "Running" },
  { name: "Running uphill, 1.4 to 1.59 mph, 30% incline", met: 14.8, category: "Running" },
  { name: "Running, stairs, up", met: 15.0, category: "Running" },
  { name: "Running uphill, 7.0 mph, 5% incline", met: 15.5, category: "Running" },
  { name: "Running, hilly terrain, ±100m change in elevation", met: 16.0, category: "Running" },
  { name: "Running uphill, >1.6mph, 10-30% incline", met: 16.3, category: "Running" },
  { name: "Running, 11 mph (5.5 min/mile)", met: 16.8, category: "Running" },
  { name: "Running curved treadmill, 9.0 to 9.9 mph", met: 16.8, category: "Running" },
  { name: "Running uphill, 5.0 to 5.9 mph, 15% incline", met: 17.5, category: "Running" },
  { name: "Running, on track, 500-1500m, competitive", met: 18.0, category: "Running" },
  { name: "Running, 12 mph (5.0 min/mile)", met: 18.5, category: "Running" },
  { name: "Running, on track, 2000-3000m, competitive", met: 19.3, category: "Running" },
  { name: "Running, 13 mph (4.6 min/mile)", met: 19.8, category: "Running" },
  { name: "Running, 14 mph (4.3 min/mile)", met: 23.0, category: "Running" },
  { name: "Tai chi, qi gong, sitting, light effort", met: 1.5, category: "Sports" },
  { name: "Horse cart, driving, standing or sitting", met: 1.8, category: "Sports" },
  { name: "Paragliding, moderate altitude", met: 1.8, category: "Sports" },
  { name: "Horseback riding, simulator", met: 2.1, category: "Sports" },
  { name: "Billiards", met: 2.5, category: "Sports" },
  { name: "Darts, wall or lawn", met: 2.5, category: "Sports" },
  { name: "Football or baseball, playing catch", met: 2.5, category: "Sports" },
  { name: "Frisbee playing, general", met: 3.0, category: "Sports" },
  { name: "Horseshoe pitching, quoits", met: 3.0, category: "Sports" },
  { name: "Shuffleboard", met: 3.0, category: "Sports" },
  { name: "Volleyball, non-competitive, 6 - 9 member team, general", met: 3.0, category: "Sports" },
  { name: "Croquet", met: 3.3, category: "Sports" },
  { name: "Lawn bowling, bocce ball, outdoor", met: 3.3, category: "Sports" },
  { name: "Sports spectator, very excited, emotional, physically moving", met: 3.3, category: "Sports" },
  { name: "Tai chi, qi gong, general", met: 3.3, category: "Sports" },
  { name: "Golf, miniature, driving range", met: 3.5, category: "Sports" },
  { name: "Hang gliding", met: 3.5, category: "Sports" },
  { name: "Skydiving, base-jumping, bungee jumping", met: 3.5, category: "Sports" },
  { name: "Walking football/soccer", met: 3.5, category: "Sports" },
  { name: "Bowling, indoor, bowling alley", met: 3.8, category: "Sports" },
  { name: "Frisbee golf", met: 3.8, category: "Sports" },
  { name: "Gymnastics, general", met: 3.8, category: "Sports" },
  { name: "Horseback riding, walking", met: 3.8, category: "Sports" },
  { name: "Coaching, football, soccer, basketball, baseball, swimming, etc.", met: 4.0, category: "Sports" },
  { name: "Curling", met: 4.0, category: "Sports" },
  { name: "Football, touch, flag, light effort", met: 4.0, category: "Sports" },
  { name: "Hacky sack", met: 4.0, category: "Sports" },
  { name: "High ropes course, multiple elements", met: 4.0, category: "Sports" },
  { name: "Juggling", met: 4.0, category: "Sports" },
  { name: "Motocross, off-road motor sports, all-terrain vehicle, general", met: 4.0, category: "Sports" },
  { name: "Rodeo sports, general, light effort", met: 4.0, category: "Sports" },
  { name: "Softball, practice", met: 4.0, category: "Sports" },
  { name: "Softball, officiating", met: 4.0, category: "Sports" },
  { name: "Track and field (e.g., shot, discus, hammer throw)", met: 4.0, category: "Sports" },
  { name: "Archery (non-hunting)", met: 4.3, category: "Sports" },
  { name: "Golf, walking, carrying clubs", met: 4.3, category: "Sports" },
  { name: "Golf, general", met: 4.5, category: "Sports" },
  { name: "Golf, walking, pulling clubs", met: 4.5, category: "Sports" },
  { name: "Horse grooming, maintenance, saddling tasks", met: 4.5, category: "Sports" },
  { name: "Tennis, doubles", met: 4.5, category: "Sports" },
  { name: "Cricket, batting, bowling, fielding", met: 4.8, category: "Sports" },
  { name: "Basketball, shooting baskets", met: 5.0, category: "Sports" },
  { name: "Rock climbing, rappelling,", met: 5.0, category: "Sports" },
  { name: "Skateboarding, general, moderate effort", met: 5.0, category: "Sports" },
  { name: "Tennis, hitting balls, non-game play, moderate effort", met: 5.0, category: "Sports" },
  { name: "Martial Arts, different types, slower pace, novice performers, practice", met: 5.3, category: "Sports" },
  { name: "Motorcycle racing, Supormoto racing", met: 5.3, category: "Sports" },
  { name: "Alaska Native Games, Eskimo Olympics, general", met: 5.5, category: "Sports" },
  { name: "Badminton, social singles and doubles, general", met: 5.5, category: "Sports" },
  { name: "Horseback riding, general", met: 5.5, category: "Sports" },
  { name: "Kung Fu Gymnastics", met: 5.5, category: "Sports" },
  { name: "Rodeo sports, general, moderate effort", met: 5.5, category: "Sports" },
  { name: "Basketball, officiating", met: 5.8, category: "Sports" },
  { name: "Boxing, punching bag", met: 5.8, category: "Sports" },
  { name: "Children’s games, adults playing  (e.g., hopscotch, 4-square, dodge ball, playground apparatus, t-ball,  tetherball, marbles,", met: 5.8, category: "Sports" },
  { name: "Horseback riding, trotting", met: 5.8, category: "Sports" },
  { name: "Rock climbing, ascending or traversing rock, low-to-moderate difficulty", met: 5.8, category: "Sports" },
  { name: "Cheerleading, gymnastic moves, competitive", met: 6.0, category: "Sports" },
  { name: "Drag racing, pushing or driving a car", met: 6.0, category: "Sports" },
  { name: "Fencing, general", met: 6.0, category: "Sports" },
  { name: "Horseback riding, reining", met: 6.0, category: "Sports" },
  { name: "Skateboarding, competitive, vigorous effort", met: 6.0, category: "Sports" },
  { name: "Softball, pitching", met: 6.0, category: "Sports" },
  { name: "Tai chi chuan, Yang style", met: 6.0, category: "Sports" },
  { name: "Volleyball, competitive, in gymnasium", met: 6.0, category: "Sports" },
  { name: "Wrestling, competitive (one match = 5 minutes)", met: 6.0, category: "Sports" },
  { name: "Track and field (e.g., high jump, long jump, triple jump, javelin, pole vault)", met: 6.0, category: "Sports" },
  { name: "Rugby, touch, non-competitive", met: 6.3, category: "Sports" },
  { name: "Trampoline, recreational", met: 6.3, category: "Sports" },
  { name: "Kendu, kihon-keiko style, moderate intensity", met: 6.5, category: "Sports" },
  { name: "Prusik climbing", met: 6.5, category: "Sports" },
  { name: "Skateboard, longboard, 13.3 km/h, slow speed", met: 6.8, category: "Sports" },
  { name: "Tennis, general, moderate effort", met: 6.8, category: "Sports" },
  { name: "Boxing, punching bag, 60 b/min", met: 7.0, category: "Sports" },
  { name: "Broomball", met: 7.0, category: "Sports" },
  { name: "Kickball", met: 7.0, category: "Sports" },
  { name: "Netball", met: 7.0, category: "Sports" },
  { name: "Rodeo sports, general, vigorous effort", met: 7.0, category: "Sports" },
  { name: "Wallyball, general", met: 7.0, category: "Sports" },
  { name: "Horseback riding, canter or gallop", met: 7.3, category: "Sports" },
  { name: "Kickboxing", met: 7.3, category: "Sports" },
  { name: "Rock climbing, ascending rock, high difficulty", met: 7.3, category: "Sports" },
  { name: "Squash, general", met: 7.3, category: "Sports" },
  { name: "Basketball, general", met: 7.5, category: "Sports" },
  { name: "Roller blading, in-line skating, 14.4 km/h (9.0 mph), recreational pace", met: 7.5, category: "Sports" },
  { name: "Boxing, sparring", met: 7.8, category: "Sports" },
  { name: "Futsal", met: 7.8, category: "Sports" },
  { name: "Hockey, field", met: 7.8, category: "Sports" },
  { name: "Coaching, actively playing sport with players", met: 8.0, category: "Sports" },
  { name: "Football, competitive", met: 8.0, category: "Sports" },
  { name: "Frisbee, ultimate", met: 8.0, category: "Sports" },
  { name: "Handball, team", met: 8.0, category: "Sports" },
  { name: "Hockey, ice, general", met: 8.0, category: "Sports" },
  { name: "Lacrosse", met: 8.0, category: "Sports" },
  { name: "Polo, on horseback", met: 8.0, category: "Sports" },
  { name: "Tennis, general, competitive", met: 8.0, category: "Sports" },
  { name: "Volleyball, beach, in sand", met: 8.0, category: "Sports" },
  { name: "Rope jumping, slow pace, < 100 skips/min, 2 foot skip, rhythm bounce", met: 8.3, category: "Sports" },
  { name: "Rugby, union, team, competitive", met: 8.3, category: "Sports" },
  { name: "Skateboard, longboard, 16.2 km/h, typical speed", met: 8.3, category: "Sports" },
  { name: "Boxing, punching bag, 120 b/min", met: 8.5, category: "Sports" },
  { name: "Auto racing, open wheel", met: 8.5, category: "Sports" },
  { name: "Rock climbing, free boulder", met: 8.8, category: "Sports" },
  { name: "Badminton, competitive, match play", met: 9.0, category: "Sports" },
  { name: "Horseback riding, jumping", met: 9.0, category: "Sports" },
  { name: "Orienteering", met: 9.0, category: "Sports" },
  { name: "Basketball, drills, practice", met: 9.3, category: "Sports" },
  { name: "Boxing, simulated boxing round, exercise", met: 9.3, category: "Sports" },
  { name: "Soccer, competitive", met: 9.5, category: "Sports" },
  { name: "Kendu, kirikaeshi style, high intensity", met: 9.6, category: "Sports" },
  { name: "Fencing, epee, competitive", met: 9.8, category: "Sports" },
  { name: "Roller blading, in-line skating, 17.7 km/h (11.0 mph), moderate pace, exercise training", met: 9.8, category: "Sports" },
  { name: "Hockey, ice, competitive", met: 10.0, category: "Sports" },
  { name: "Paddleball, competitive", met: 10.0, category: "Sports" },
  { name: "Racquetball, competitive", met: 10.0, category: "Sports" },
  { name: "Rope jumping, double under or more", met: 10.0, category: "Sports" },
  { name: "Track and field (e.g., steeplechase, hurdles)", met: 10.0, category: "Sports" },
  { name: "Martial Arts, different types, moderate pace (e.g., judo, jujitsu, karate, kick boxing, tae kwon do, tai-bo, Muay Thai boxing)", met: 10.3, category: "Sports" },
  { name: "Race Walking, 3.1 m/s (6.9 mph)", met: 10.3, category: "Sports" },
  { name: "Trampoline, competitive", met: 10.3, category: "Sports" },
  { name: "Floorball", met: 10.5, category: "Sports" },
  { name: "Rock climbing, speed climbing, very difficult", met: 10.5, category: "Sports" },
  { name: "Rock climbing, treadwall, 4-6 m/min", met: 10.5, category: "Sports" },
  { name: "Rock climbing, treadwall, 7-10 m/min", met: 10.5, category: "Sports" },
  { name: "Skateboard, longboard, 13.3 km/h, fast speed", met: 10.5, category: "Sports" },
  { name: "Boxing, punching bag, 180 b/min", met: 10.8, category: "Sports" },
  { name: "Judo", met: 11.3, category: "Sports" },
  { name: "Kendu, kakari keiko style, very high intensity", met: 11.3, category: "Sports" },
  { name: "Rope jumping, moderate pace, general, 100 to 120 skips/min, 2 foot skip, plain bounce", met: 11.8, category: "Sports" },
  { name: "Jai alai", met: 12.0, category: "Sports" },
  { name: "Boxing, in ring, general", met: 12.3, category: "Sports" },
  { name: "Rope jumping, fast pace, 120-160 skips/min", met: 12.3, category: "Sports" },
  { name: "Roller blading, in-line skating, 21.0 to 21.7 km/h (13.0 to 13.6 mph), fast pace, exercise training", met: 12.3, category: "Sports" },
  { name: "Race Walking, 3.7 m/s (8.3 mph)", met: 13.8, category: "Sports" },
  { name: "Taekwondo, combat simulation", met: 14.3, category: "Sports" },
  { name: "Race Walking, racing speed, 4.0 m/s (8.95 mph)", met: 15.5, category: "Sports" },
  { name: "Rollerblading, in-line skating, 24.0 km/h (15.0 mph), maximal effort", met: 15.5, category: "Sports" },
  { name: "Walking, with a walker or step-to gait on treadmill, 0.7 mph (1.1 km/h), 0% grade", met: 1.5, category: "Walking" },
  { name: "Walking, treadmill, less than 1.0 mph, 0% grade", met: 2.1, category: "Walking" },
  { name: "Carrying ~10 lb child, slow walking", met: 2.3, category: "Walking" },
  { name: "Walking, household", met: 2.3, category: "Walking" },
  { name: "Walking, less than 2.0 mph, level, strolling, very slow", met: 2.3, category: "Walking" },
  { name: "Walking, treadmill, 1.0 mph, 0% grade", met: 2.3, category: "Walking" },
  { name: "Bird watching, walking and stopping", met: 2.5, category: "Walking" },
  { name: "Walking from house to car or bus, from car or bus to go places, from car or bus to and from the worksite", met: 2.5, category: "Walking" },
  { name: "Walking to neighbor’s house or family’s house for social reasons", met: 2.5, category: "Walking" },
  { name: "Walking, to and from an outhouse", met: 2.5, category: "Walking" },
  { name: "Walking, 2.0 to 2.4 mph, level, slow pace, firm surface", met: 2.8, category: "Walking" },
  { name: "Walking, treadmill, 1.2 to 1.9 mph, 0% grade (1.9 to 3.0 km/h)", met: 2.8, category: "Walking" },
  { name: "Walking the dog", met: 3.0, category: "Walking" },
  { name: "Walking, 2.5 mph, firm, level surface", met: 3.0, category: "Walking" },
  { name: "Walking, treadmill, 2.0 to 2.4 mph (3.2 to 3.9 km/h), 0% grade", met: 3.0, category: "Walking" },
  { name: "Walking, 2.5 mph, downhill", met: 3.3, category: "Walking" },
  { name: "Walking, treadmill, downhill (-3% to -12% grade), 2.8 to 3.1 mph", met: 3.3, category: "Walking" },
  { name: "Walking, treadmill, downhill (-5% to -25% grade), 2.8 mph, with Nordic Poles", met: 3.3, category: "Walking" },
  { name: "Walking with a day pack, level ground, assumed in the city", met: 3.5, category: "Walking" },
  { name: "Descending stairs", met: 3.5, category: "Walking" },
  { name: "Walking, Putey walk, Monty Python Ministry of Silly Walks", met: 3.5, category: "Walking" },
  { name: "Walking, treadmill, 2.5 to 2.9 mph (4.0 to 4.7 km/h), 0% grade", met: 3.5, category: "Walking" },
  { name: "Loading  and/or unloading a car, implied walking", met: 3.8, category: "Walking" },
  { name: "Climbing hills, 15-50 lb load, 1 to 2% grade, slow pace", met: 3.8, category: "Walking" },
  { name: "Hiking slowly or ambling through fields and hillsides, no load", met: 3.8, category: "Walking" },
  { name: "Pushing or pulling stroller with child or walking with children, 2.5 to 3.1 mph", met: 3.8, category: "Walking" },
  { name: "Pushing a wheelchair, non-occupational", met: 3.8, category: "Walking" },
  { name: "Walking, 2.8 to 3.4 mph, level, moderate pace, firm surface", met: 3.8, category: "Walking" },
  { name: "Walking, treadmill, 3.0 to 3.4 mph (4.8 to 5.5 km/h), 0% grade", met: 3.8, category: "Walking" },
  { name: "Carrying 5 to 14 lb (2.3 to 6.4 kg) load (e.g. suitcase, boxes, groceries), level ground, moderate pace", met: 4.0, category: "Walking" },
  { name: "Walking, self-selected speed, indoor track or outdoors, firm surface", met: 4.0, category: "Walking" },
  { name: "Using medical knee scooter", met: 4.3, category: "Walking" },
  { name: "Walking, for exercise, 2.5 to 3.5 mph (4.0 to 5.6 km/h), with ski poles, Nordic walking, level, moderate pace", met: 4.3, category: "Walking" },
  { name: "Carrying 15 - 155 lb (6.8 - 70.4 kg) load (e.g. suitcase, boxes, furniture), level ground or downstairs, slow pace", met: 4.5, category: "Walking" },
  { name: "Hauling water, head hauling, walking on flat surface", met: 4.5, category: "Walking" },
  { name: "Marching, moderate speed, military, no pack", met: 4.5, category: "Walking" },
  { name: "Stair climbing, slow pace", met: 4.5, category: "Walking" },
  { name: "Using crutches, level ground, general", met: 4.5, category: "Walking" },
  { name: "Walking, normal pace, plowed field or sand", met: 4.5, category: "Walking" },
  { name: "Walking, 3.5 to 3.9 mph, level, brisk, firm surface, walking for exercise", met: 4.8, category: "Walking" },
  { name: "Walking, grass track", met: 4.8, category: "Walking" },
  { name: "Walking, treadmill, 3.5 to 3.9 mph (5.6 to 6.3 km/h), 0% grade", met: 4.8, category: "Walking" },
  { name: "Walking, treadmill, 2.5 mph, 0% grade, 5 to 20 degrees C, 40 lb (18.2 kg) load", met: 4.8, category: "Walking" },
  { name: "Climbing hills, no load, 5 to 20% grade, very slow pace", met: 5.0, category: "Walking" },
  { name: "Climbing hills, no load, 1 to 5% grade, moderate-to-brisk pace", met: 5.3, category: "Walking" },
  { name: "Hiking or walking at a normal pace through fields and hillsides, no load", met: 5.3, category: "Walking" },
  { name: "Walking, for exercise, 3.6 to 4.4 mph (5.8 to 7.1 km/h), with ski poles, Nordic walking, level, moderate pace", met: 5.3, category: "Walking" },
  { name: "Carrying load, 1 to 15 lb load, upstairs", met: 5.5, category: "Walking" },
  { name: "Walking, 4.0 to 4.4 mph (6.4 to 7.0 km/h), level, firm surface, very brisk pace", met: 5.5, category: "Walking" },
  { name: "Walking, treadmill, 4.0 to 4.4 mph (6.4 to 7.1 km/h), 0% grade", met: 5.8, category: "Walking" },
  { name: "Walking, treadmill, 2.5 mph, 0% grade, -10 to 0 degrees C, 40 lb (18.2 kg) load", met: 5.8, category: "Walking" },
  { name: "Carrying load, 16 to 24 lb load, upstairs", met: 6.0, category: "Walking" },
  { name: "Walking, backward, 3.5 mph, level", met: 6.0, category: "Walking" },
  { name: "Carrying 50 to 150 pound load (e.g., equine or bovine feed, fence pipes, furniture), level ground, moderate pace", met: 6.5, category: "Walking" },
  { name: "Climbing hills, 10 to 20 lb load, 5 to 10% grade, moderate", met: 6.5, category: "Walking" },
  { name: "Race walking", met: 6.5, category: "Walking" },
  { name: "Stair climbing, general", met: 6.8, category: "Walking" },
  { name: "Walking, treadmill, 4.5 to 4.9 mph (7.2 to 7.9 km/h), 0% grade", met: 6.8, category: "Walking" },
  { name: "Climbing hills, no load, 6 to 10% grade, moderate-to-brisk pace", met: 7.0, category: "Walking" },
  { name: "Using crutches, fast pace", met: 7.0, category: "Walking" },
  { name: "Walking, 4.5 to 4.9 mph, level, firm surface, very, very brisk", met: 7.0, category: "Walking" },
  { name: "Climbing hills, 21 to 40 lb load, 3 to 10% grade, moderate-to-brisk pace", met: 7.5, category: "Walking" },
  { name: "Stair climbing, two steps at a time", met: 7.5, category: "Walking" },
  { name: "Stair climbing, ascending and descending stairs", met: 7.5, category: "Walking" },
  { name: "Backpacking,  hiking with a daypack, organized walking with daypack", met: 7.8, category: "Walking" },
  { name: "Walking, backward, 3.5 mph, uphill, 5% grade", met: 7.8, category: "Walking" },
  { name: "Walking treadmill, backwards, 2.5 mph, +10% grade", met: 7.8, category: "Walking" },
  { name: "Carrying load, 25 to 49 lb load, upstairs", met: 8.0, category: "Walking" },
  { name: "Marching rapidly, military, no pack", met: 8.0, category: "Walking" },
  { name: "Walking, Teabag walk, Monty Python Ministry of Silly Walks", met: 8.0, category: "Walking" },
  { name: "Carrying load upstairs, general", met: 8.3, category: "Walking" },
  { name: "Walking, treadmill, 5.0 to 5.5 mph (8.0 to 8.9 km/h), 0% grade", met: 8.3, category: "Walking" },
  { name: "Walking, Curved treadmill, 3.0 to 5.0 mph, brisk pace", met: 8.3, category: "Walking" },
  { name: "Climbing hills, no load, steep grade (30%), slow pace (less than 1.2 mph)", met: 8.5, category: "Walking" },
  { name: "Walking, 5.0 to 5.5 mph (8.8 to 8.9 km/h), level, firm surface", met: 8.5, category: "Walking" },
  { name: "Walking, for exercise, 4.5 to 5.0 mph, with ski poles, Nordic walking, level, fast pace", met: 8.5, category: "Walking" },
  { name: "Climbing hills, no load, 11 to 20% grade, slow-to-moderate pace", met: 8.8, category: "Walking" },
  { name: "Walking, for exercise, with ski poles, Nordic walking, uphill, moderate pace", met: 8.8, category: "Walking" },
  { name: "Stair climbing, fast pace, one step at a time", met: 9.3, category: "Walking" },
  { name: "Carrying load, 50 to 74 lb load, upstairs", met: 10.0, category: "Walking" },
  { name: "Climbing hills, no load, 4.0 to 5.0 mph, 3 to 5% grade, very fast pace", met: 10.0, category: "Walking" },
  { name: "Climbing hills, 20+ pound load, 5 to 20% grade, moderate to brisk pace", met: 10.0, category: "Walking" },
  { name: "Walking, for exercise, with ski poles, Nordic walking, level ground, carrying 20 to 30 lb load (9.0 to 15.0 kg)", met: 10.8, category: "Walking" },
  { name: "Carrying load, >74 lb load, upstairs", met: 12.0, category: "Walking" },
  { name: "Walking, for exercise, with ski poles, Nordic walking, uphill, carrying 20 to 30 lb load (9.0 to 15.0 kg)", met: 12.3, category: "Walking" },
  { name: "Climbing hills, no load, very steep grade (30-40%), 1.2 to 1.8 mph", met: 15.5, category: "Walking" },
  { name: "Climbing hills, no load, steep grade (10-40%), 1.8 to 5.0 mph", met: 16.3, category: "Walking" },
  { name: "Boating, power, passenger, light", met: 1.3, category: "Water Activities" },
  { name: "Sailing, dingy", met: 2.0, category: "Water Activities" },
  { name: "Tubing, floating on a river, general", met: 2.3, category: "Water Activities" },
  { name: "Boating, power, driving", met: 2.5, category: "Water Activities" },
  { name: "Water walking, light effort, slow pace", met: 2.5, category: "Water Activities" },
  { name: "Canoeing, rowing, 2.0-3.9 mph, light effort", met: 2.8, category: "Water Activities" },
  { name: "Stand up Paddleboard, standing, 10-19 strokes/min", met: 2.8, category: "Water Activities" },
  { name: "Diving, springboard or platform", met: 3.0, category: "Water Activities" },
  { name: "Surfing, body or board, general", met: 3.0, category: "Water Activities" },
  { name: "Water volleyball", met: 3.0, category: "Water Activities" },
  { name: "Canoeing, harvesting wild rice, knocking rice off the stalks", met: 3.3, category: "Water Activities" },
  { name: "Sailing, Sunfish/Laser/Hobby Cat, Keel boats, ocean sailing, yachting, leisure", met: 3.3, category: "Water Activities" },
  { name: "Swimming, treading water, moderate effort,  general", met: 3.5, category: "Water Activities" },
  { name: "Stand up Paddleboard, standing, 20-29 strokes/min", met: 3.8, category: "Water Activities" },
  { name: "Water aerobics, resistance exercises", met: 3.8, category: "Water Activities" },
  { name: "Paddle boat", met: 4.0, category: "Water Activities" },
  { name: "Sailing, in competition, general", met: 4.5, category: "Water Activities" },
  { name: "Swimming, backstroke, recreational", met: 4.8, category: "Water Activities" },
  { name: "Water walking, moderate effort, moderate pace", met: 4.8, category: "Water Activities" },
  { name: "Kayaking, moderate effort", met: 5.0, category: "Water Activities" },
  { name: "Surfing, body or board, competitive", met: 5.0, category: "Water Activities" },
  { name: "Stand up Paddleboard, standing, 30-39 strokes/min", met: 5.0, category: "Water Activities" },
  { name: "Whitewater rafting, kayaking, or canoeing", met: 5.0, category: "Water Activities" },
  { name: "Windsurfing, not pumping for speed", met: 5.0, category: "Water Activities" },
  { name: "Scuba diving, general, light effort", met: 5.3, category: "Water Activities" },
  { name: "Swimming breaststroke, recreational", met: 5.3, category: "Water Activities" },
  { name: "Scuba diving, professional diver", met: 5.5, category: "Water Activities" },
  { name: "Water aerobics, water calisthenics, general", met: 5.5, category: "Water Activities" },
  { name: "Canoeing, rowing, 4.0-5.9 mph, moderate effort", met: 5.8, category: "Water Activities" },
  { name: "Scuba diving, general, moderate effort", met: 5.8, category: "Water Activities" },
  { name: "Swimming laps, freestyle, slow, recreational", met: 5.8, category: "Water Activities" },
  { name: "Swimming, crawl, slow speed, 30-45 yards/minute, moderate effort", met: 5.8, category: "Water Activities" },
  { name: "Swimming, leisurely, not lap swimming, general", met: 6.0, category: "Water Activities" },
  { name: "Stand up paddle boarding, general", met: 6.5, category: "Water Activities" },
  { name: "Water running, 30 steps/min, slow", met: 6.5, category: "Water Activities" },
  { name: "Scuba diving, recreational diver", met: 6.8, category: "Water Activities" },
  { name: "Surfboard, paddling", met: 6.8, category: "Water Activities" },
  { name: "Water walking, vigorous effort, brisk pace", met: 6.8, category: "Water Activities" },
  { name: "Canoeing, portaging", met: 7.0, category: "Water Activities" },
  { name: "Jet skiing, driving, in water", met: 7.0, category: "Water Activities" },
  { name: "Swimming, sidestroke, general", met: 7.0, category: "Water Activities" },
  { name: "Water aerobics, high intensity", met: 7.5, category: "Water Activities" },
  { name: "Water running, 40 steps/min, moderate", met: 7.5, category: "Water Activities" },
  { name: "Swimming, crawl, medium speed, ~50 yards/minute, vigorous effort", met: 8.0, category: "Water Activities" },
  { name: "Swimming, synchronized", met: 8.0, category: "Water Activities" },
  { name: "Water running, 50 steps/min, fast", met: 8.5, category: "Water Activities" },
  { name: "Kayaking, slalom, flat water", met: 9.0, category: "Water Activities" },
  { name: "Sailing, in competition, high effort", met: 9.3, category: "Water Activities" },
  { name: "Swimming, backstroke, training or competition", met: 9.5, category: "Water Activities" },
  { name: "Stand up Paddleboard, standing, 40-49 strokes/min", met: 9.8, category: "Water Activities" },
  { name: "Swimming laps, freestyle, fast, vigorous effort", met: 9.8, category: "Water Activities" },
  { name: "Swimming, treading water, fast, vigorous effort", met: 9.8, category: "Water Activities" },
  { name: "Water jogging, vigorous effort", met: 9.8, category: "Water Activities" },
  { name: "Water running, 60 steps/min, very fast", met: 9.8, category: "Water Activities" },
  { name: "Water polo", met: 10.0, category: "Water Activities" },
  { name: "Swimming, breaststroke, general, training or  competition", met: 10.3, category: "Water Activities" },
  { name: "Swimming, crawl, fast speed, ~75 yards/minute,  vigorous effort", met: 10.5, category: "Water Activities" },
  { name: "Swimming, open water, 5k", met: 10.5, category: "Water Activities" },
  { name: "Stand up Paddleboard, standing, 50-69 strokes/min", met: 11.0, category: "Water Activities" },
  { name: "Windsurfing or kitesurfing, crossing trial", met: 11.0, category: "Water Activities" },
  { name: "Skindiving, moderate", met: 11.8, category: "Water Activities" },
  { name: "Canoeing, rowing, kayaking, competition, > 6 mph, vigorous effort", met: 12.5, category: "Water Activities" },
  { name: "Kayaking, competition", met: 13.5, category: "Water Activities" },
  { name: "Swimming, butterfly, general", met: 13.8, category: "Water Activities" },
  { name: "Windsurfing, competition, pumping for speed", met: 14.0, category: "Water Activities" },
  { name: "Swimming, crawl, elite swimmers, competition, >90 yards/minute", met: 14.5, category: "Water Activities" },
  { name: "Rowing, simulated crew in a water tank, single oar, 33 strokes/min,", met: 15.5, category: "Water Activities" },
  { name: "Rowing, single scull, ergometer, ergometer on slides, racing speed (32+ strokes/min, >10 mph)", met: 15.5, category: "Water Activities" },
  { name: "Skindiving, fast", met: 15.8, category: "Water Activities" },
  { name: "Ice fishing", met: 2.0, category: "Winter Activities" },
  { name: "Snowmobiling, passenger, light", met: 2.0, category: "Winter Activities" },
  { name: "Dog sledding, passenger", met: 2.5, category: "Winter Activities" },
  { name: "Snow blower, walking and pushing", met: 2.5, category: "Winter Activities" },
  { name: "Snowmobiling, driving, moderate pace, flat land", met: 3.8, category: "Winter Activities" },
  { name: "Skiing, downhill, alpine or snowboarding, light effort, active time only", met: 4.3, category: "Winter Activities" },
  { name: "Snow shoeing, moderate effort", met: 5.3, category: "Winter Activities" },
  { name: "Snow shoveling, by hand, moderate effort", met: 5.3, category: "Winter Activities" },
  { name: "Skating, ice, 9 mph or less", met: 5.5, category: "Winter Activities" },
  { name: "Rollerskiing, 10 - 12.9 km/h, no incline", met: 5.5, category: "Winter Activities" },
  { name: "Moving icehouse, set up/drill holes", met: 6.0, category: "Winter Activities" },
  { name: "Skiing, downhill, alpine or snowboarding, moderate effort, general, active time only", met: 6.3, category: "Winter Activities" },
  { name: "Skiing, cross country, 2.5 mph, slow or light effort, ski walking", met: 6.8, category: "Winter Activities" },
  { name: "Rollerskiing, 13 - 16.9 km/h, no incline", met: 6.8, category: "Winter Activities" },
  { name: "Ski jumping, climb up carrying skis", met: 7.0, category: "Winter Activities" },
  { name: "Skiing, general", met: 7.0, category: "Winter Activities" },
  { name: "Skiing, Alpine skiing high-intensity training", met: 7.3, category: "Winter Activities" },
  { name: "Dog sledding, mushing", met: 7.5, category: "Winter Activities" },
  { name: "Snowboarding, recreational, moderate pace, mountain", met: 7.5, category: "Winter Activities" },
  { name: "Snow shoveling, by hand, vigorous effort", met: 7.5, category: "Winter Activities" },
  { name: "Skiing, downhill, alpine or snowboarding, vigorous effort, active time only", met: 8.0, category: "Winter Activities" },
  { name: "Rollerskiing, 17 - 19.9 km/h, no incline", met: 8.3, category: "Winter Activities" },
  { name: "Skiing, cross country, 4.0-4.9 mph, moderate speed and effort, general", met: 8.5, category: "Winter Activities" },
  { name: "Skating, ice, rapidly, more than 9 mph but not competitive", met: 9.0, category: "Winter Activities" },
  { name: "Skating Treadmill, 6 - 6.9 mph, 2% grade", met: 9.0, category: "Winter Activities" },
  { name: "Mountaineering, downhill climbing, walking down with rope", met: 9.0, category: "Winter Activities" },
  { name: "Skiing, slalom", met: 9.3, category: "Winter Activities" },
  { name: "Skiing, cross-country skiing high-intensity training", met: 9.5, category: "Winter Activities" },
  { name: "Skating Treadmill, 7 - 7.9 mph, 2% grade", met: 10.0, category: "Winter Activities" },
  { name: "Snow shoeing, vigorous effort", met: 10.0, category: "Winter Activities" },
  { name: "Mountaineering, downhill climbing/cross-country skiing", met: 10.3, category: "Winter Activities" },
  { name: "Skating Treadmill, 8 - 8.9 mph, 2% grade", met: 10.5, category: "Winter Activities" },
  { name: "Rollerskiing, 20 - 23.9 km/h, no incline", met: 10.5, category: "Winter Activities" },
  { name: "Skating Treadmill, 9 - 9.9 mph, 2% grade", met: 11.0, category: "Winter Activities" },
  { name: "Skiing, cross country, 5.0-7.9 mph, brisk speed, vigorous effort", met: 11.3, category: "Winter Activities" },
  { name: "Rollerskiing, 6-9 km/h, 6-10 degree incline", met: 12.3, category: "Winter Activities" },
  { name: "Skiing, roller, elite racers", met: 12.5, category: "Winter Activities" },
  { name: "Rollerskiing, 10-15 km/h, 2-5 degree incline", met: 12.5, category: "Winter Activities" },
  { name: "Biathlon training, 5 degree incline, 8 km/h (5 mph), with/without rifle", met: 12.8, category: "Winter Activities" },
  { name: "Biathlon training, 5 degree incline, 10.7 km/h (5 mph), with/without rifle", met: 12.8, category: "Winter Activities" },
  { name: "Skiing, cross-country, skating", met: 13.3, category: "Winter Activities" },
  { name: "Skiing, cross-country, biathlon, skating technique", met: 13.5, category: "Winter Activities" },
  { name: "Skating, speed, competitive", met: 13.8, category: "Winter Activities" },
  { name: "Skating, ice dancing", met: 14.0, category: "Winter Activities" },
  { name: "Skiing, cross country, elite skier, >8.0-11.9 mph, racing", met: 14.0, category: "Winter Activities" },
  { name: "Rollerskiing, 16-22 km/h, 2-5 degree incline", met: 14.3, category: "Winter Activities" },
  { name: "Rollerskiing, 24 - 27.9 km/h, no incline", met: 15.0, category: "Winter Activities" },
  { name: "Skiing, cross country, hard snow, uphill, maximum, snow mountaineering", met: 15.5, category: "Winter Activities" },
  { name: "Skiing, cross country, 12-16 mph, elite skier, racing", met: 16.0, category: "Winter Activities" },
  { name: "Rollerskiing, >10 km/h, 6-10 degree incline", met: 16.0, category: "Winter Activities" },
];
